
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owuvfujjvlpjbkvxdafz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93dXZmdWpqdmxwamJrdnhkYWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MDk5NzYsImV4cCI6MjA1NjE4NTk3Nn0.oS3i2I6_ns7ixo1fw_rEJdlhOIcrIiKJqCh7aniafwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'X-Supabase-Client-Info': 'lovable-app',
      },
    },
  }
);
